# The URL the site will be built for
base_url = "https://bojohnson5.github.io"

theme = "project-portfolio"

title = "Bytes of Physics"

taxonomies = [
  { name = "projects", paginate_by = 5, feed = true },
  { name = "skills", paginate_by = 5, feed = true },
  { name = "blog-tags", paginated_by = 5, feed = true },
]

[translations]
language_symbol = "🇬🇧"
home = "Home"
projects = "Projects"
skills = "Skills"
read_more = "Read More"
skills_technologies = "Skills & Technologies"
main_skills = "Main Skills"
other_skills = "Additional Skills"
words = "words"
minutes = "minutes"

[extra.navbar]
title = "Bytes of Physics"

items = [{ lang = "en", links = [{ url = "blog", name = "Blog" }] }]

[extra.index]
title = "Bytes of Physics"
slogan = "The intersection of physics and computing work"
image = "blog.webp"
image_alt = "Placeholder text describing the index's image."

[extra.social]
# codeberg = "https://codeberg.org/johndoe"
github = "https://github.com/bojohnson5"
# gitlab = "https://gitlab.com/johndoe"
# twitter = "https://twitter.com/johndoe"
# mastodon = "https://social.somewhere.com/users/johndoe"
# linkedin = "https://www.linkedin.com/in/john-doe-b1234567/"
# stackoverflow = "https://stackoverflow.com/users/01234567/johndoe"
# telegram = "https://t.me/johndoe"
email = "bo.johnson5@icloud.com"

[markdown]
highlight_code = true
highlight_theme = "css"
highlight_themes_css = [
  { theme = "ayu-dark", filename = "syntax-dark.css" },
  { theme = "ayu-light", filename = "syntax-light.css" },
]
